### ISSUE TITLE
Add "Translate Link Text" feature

### ISSUE THREAD

**Issue by def00111** [sienori/simple-translate#11]

**Comment by sienori** [comment]
Is the feature to translate [such link text]()?
You can select the link text by holding down ALT and dragging it.

**Comment by def00111** [comment]
menus.OnClickData [1] has a linkText property, maybe you can use this?
[1] https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/OnClickData

**Comment by sienori** [comment]
Hmm, I think that function is unnecessary.
I do not want to increase the items of the context menu more than necessary.
It can be realized by holding down ALT and dragging it.

**Comment by NgYueHong** [comment]
@sienori Your plugin is super COOL. It is the plugin I have been looking for. 

I think adding "translate link text" is important and I am also looking for it (that's why I am here). It allow us more easily translate link text. Also, not everyone knows holding down ALT key can select link text. (I just knew it after reading your comment on this issue.)

If you don't want adding more item in the context menu. You can have this feature turn off by default and user can turn on it via option page.

Hope you can re-consider it. Really looking forward for this feature.

**Comment by def00111** [comment]
Or some one makes a pull request?
