### ISSUE TITLE
Error: Service usage limit reached. Please wait a while and try again

### ISSUE THREAD

**Issue by sunqianGitHub** [sienori/simple-translate#116]
i have a Error when use 👍 simple-translate
i'm shure my vpn work ok, i can connected to google

**Error: Service usage limit reached. Please wait a while and try again**

the translate doesn't work when this massage happen
please fixed,thanks very mach 

simple-translate Version 1.9.0 on firefox 63.0 
on more say: your simple-translate is very useful and terse
![default](https://user-images.githubusercontent.com/30254405/47763728-ce8cbf80-dcfc-11e8-9b3e-4c1d123710b6.png)

**Comment by sienori** [comment]
In version 1.9.1, I improved to reduce the access to translation API.
This improvement will reduce the frequency of errors.

**Comment by TheMightyQuasar** [comment]
The issue is present in Version 2.1.1
Firefox version 69.0.1 (64-bit).

**Comment by headsign** [comment]
I have this issue right now. Hardly used the extension today. Just a few words and it came up.
Firefox 70 (MacOS 64bit), ST 2.20

**Comment by aalexgabi** [comment]
I have the same problem. I tend to select text while reading and I have activated the translate panel when selecting text so it's my fault. I wonder if there is a way to exclude some languages from translation (english in my case) so that API calls are done only when the language is not detected.

I should switch back to the translate button to avoid this in the future.

**Comment by nildiert** [comment]
I can't understand the solution because is writed in english and I always use the spanish translator with simple translate :(
