### ISSUE TITLE
[Feature Request] Use other APIs to translate

### ISSUE THREAD

**Issue by Nutr1t07** [sienori/simple-translate#149]
I'm using this extension to read some documents and it always show `Error: Service usage limit reached.` after using for a while. It would be nice to also add other options to use different translation APIs. And the APPID can be signed up and config by users.

**Comment by ulpyuxa** [comment]
Yes, I have the same problem

**Comment by WPFilmmaker** [comment]
From what I understood it means you use the addon too often within a short amount of time. I am in favour of using google as main API and another provider as a backup.

The problem is that afaik google offers the best API for such free products. Such free apis always have limits per requests. If you want more you need to pay, and since the addon is free is not fair to ask sienori to pay. 

Yandex Translate could be an alternative however there are issues with limits too, from their website: "The daily request limit is 1,000,000 characters. The monthly limit is 10,000,000 characters" if the addon uses more characters you need to witch to fee-paying mode. 

Translating 200 words is over 1000 characters...so that's 1000 users a day translating once or less (since most users use it more than once a day).

Unless there is a crowdfunding campaign to pay for paid APIS, I doubt the translation rates will increase.

**Comment by Ne1s07** [comment]
No I don't mean to ask sienori to pay for it. Users themselves can just sign up APIs and config them in plugin option page. Also there are many free translate APIs like [Youdao](http://fanyi.youdao.com/translate?&doctype=json&type=AUTO&i=powered%20by%20youdao) and [Bing](https://azure.microsoft.com/free/).

**Comment by Ne1s07** [comment]
> From what I understood it means you use the addon too often within a short amount of time. I am in favour of using google as main API and another provider as a backup.
> 
> The problem is that afaik google offers the best API for such free products. Such free apis always have limits per requests. If you want more you need to pay, and since the addon is free is not fair to ask sienori to pay.
> 
> Yandex Translate could be an alternative however there are issues with limits too, from their website: "The daily request limit is 1,000,000 characters. The monthly limit is 10,000,000 characters" if the addon uses more characters you need to witch to fee-paying mode.
> 
> Translating 200 words is over 1000 characters...so that's 1000 users a day translating once or less (since most users use it more than once a day).
> 
> Unless there is a crowdfunding campaign to pay for paid APIS, I doubt the translation rates will increase.

No I don't mean to ask sienori to pay for it. Users themselves can just sign up APIs and config them in plugin option page. Also there are many free translate APIs like Youdao and Bing.

**Comment by Ne1s07** [comment]
No I don't mean to ask sienori to pay for it. Users themselves can just sign up APIs and config them in plugin option page. Also there are many free translate APIs like Youdao and Bing.

**Comment by WPFilmmaker** [comment]
"Users themselves can just sign up APIs and config them in plugin option page." Now I understand! I like the idea! (Maybe better to rename this ticket?)

**Comment by Ne1s07** [comment]
Well, I think it may be not that feasible to ask user to get appid for translation platform...Another possible way is to use more APIs so we can use different APIs to translate when one is out of limit. For instance using Google translate and Yandex mixly may be better.

**Comment by ulpyuxa** [comment]
Another method, Author can also simulate call the Google Translate page's input box to achieve translation function.

**Comment by Ne1s07** [comment]
See this

**Comment by Ne1s07** [comment]
See [this](https://www.w3xue.com/exp/article/20189/374.html)

**Comment by baterflyrity** [comment]
Hi. I like this extension. It is as simple and useful as possible. 
But I do not like google translation because its really bad for my language. Also i like yandex so I want to join suggestion of adding custom providers or event configuration of providers in settings.

In addition I wanna have availability to translate by Shift only key.

What do authors think about it?

p.s.
See also api binding in [code](https://github.com/sienori/simple-translate/blob/308bac05b23f9cd5ffa336654ff71450f409e341/src/common/translate.js#L28).

**Comment by baterflyrity** [comment]
Very nice idea, but unfortunately they have paid API and forbid to use it in some countries like mine((

**Comment by sienori** [comment]
I finally implemented support for DeepL!
By registering with the DeepL API, you can use DeepL with Simple Translate.  [How to register DeepL](https://github.com/sienori/simple-translate/wiki/How-to-register-DeepL-API)
![image](https://user-images.githubusercontent.com/29514424/156584969-b40c57da-0956-40a5-b125-1230242b0726.png)

**Comment by Nutr1t07** [comment]
Congratulations! It's awesome to have the new api available. Btw, I saw an implementation to multiple translate service without using api key in [NekoX's source code](https://github.com/NekoX-Dev/NekoX/search?q=translate+&type=), and I think it would be great if you could add these as well :)
