### ISSUE TITLE
Rate limited

### ISSUE THREAD

**Issue by CaliSock** [sienori/simple-translate#174]
Selection translate and in-addon translate are rate limited.

![圖片.png](https://i.loli.net/2019/08/16/RoNlZ3HskzQe5Ym.png)
![圖片.png](https://i.loli.net/2019/08/16/4OsmcX897nV5ZhM.png)

"錯誤：已達服務使用限制。請稍後再試一次。" means that **the service is currently unavailable due to the limit.**

**Comment by WPFilmmaker** [comment]
From simple-translate page:
"USERS: If you translate it many times in a short time, it may become unusable for a while due to the specification change of the translation API. If it occurs frequently, it is recommended to increase the translation waiting time on option page."

it is a duplicate of #135.
