### ISSUE TITLE
simple-translate div is breaking site's layout

### ISSUE THREAD

**Issue by mbledkowski** [sienori/simple-translate#207]
Hi, when the site have "body" styled with 

> display: flex; justify-content: space-between/ space-around;

 the div generated by this extension breaks a site's layout (empty space at the bottom). It could be fix, by adding "position: absolute;" style to it.

**Comment by sienori** [comment]
I could not reproduce this bug. Please tell me the URL where the problem occurs.

**Comment by sn260591** [comment]
It is better to append the translation panel to the `document.documentElement` instead of `document.body` to reduce the possibility of conflicts with the page code.

**Comment by sienori** [comment]
@sn260591 
Placing the translation panel outside the body causes bugs in some environments... https://github.com/sienori/simple-translate/pull/151

**Comment by sn260591** [comment]
> Placing the translation panel outside the body causes bugs in some environments... #151

Looks like a ReactDOM problem. If open [https://www.bilibili.com](https://www.bilibili.com) and execute `document.body.insertAdjacentHTML("afterend", "<div id='simple-translate'></div>")` in the console, then a new `<body>` is not created.

**Comment by mmble** [comment]
> I could not reproduce this bug. Please tell me the URL where the problem occurs.

I do not have any certain example, but the problem occurs for example in this case: 

```
<html><head></head>
<body style="height: 100vh; display: flex; justify-content: space-between; flex-flow: column nowrap;">
    <h1>test</h1>
    <h2>test2</h2>
    <h3>test3</h3>
</body></html>
```

**Comment by benjibee** [comment]
[Here's a simple Codepen example](https://codepen.io/benjibee/pen/ZEJgRKd?editors=1000) of the issue @mbledkowski is seeing. If you select any text on the page, the layout will jump to accomidate the `div` added by Simple Translate.

**Comment by benjibee** [comment]
I discovered this extension because a client kept reporting strange layout issues or white boxes appearing on the page that I couldn't reproduce. This plugin seems to be the source of these issues, sadly.

@mbledkowski I think my issue is related to yours, if you don't think it is please let me know and I'll open a separate issue

## Examples of broken layouts

Below is a broken grid layout example. My CSS references a child `div` element but since it's not using the direct descendent selector (`.element div` and not `.element > div`) it's applying to all of the `div`s in the Simple Translate window…

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/620119/143596080-4b2bbcf3-1892-438c-b094-2fd97004358d.png">

And here's a random white box that has been appended to the end of a `div` containing three `p` elements with German text:

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/620119/143596701-b197860f-15b5-4e74-8725-08bced8e56fa.png">

**Comment by sienori** [comment]
I fixed it. Thanks! https://github.com/sienori/simple-translate/commit/e131725796beabbb106f51915dc8baf81cca2084
