### ISSUE TITLE
Copying text without formatting

### ISSUE THREAD

**Issue by xeophyte** [sienori/simple-translate#452]
Hi, is this possible to copy without formatting from this extension? I have these annoying situations all the time:

![vivaldi - 2023 01 28_13 57 02](https://user-images.githubusercontent.com/121556803/215267584-38adc100-5f2f-45e5-8f0f-e2592a9d0893.gif)

**Comment by atf98** [comment]
@xeophyte, this problem only happened in chrome. It happened because the package used to copy the clipboard is not fully compatible with google chrome; it never happened to me in firefox.
However, this is a workaround for this problem by adding one line to the handle copy function in the CopyByutton.js file:
@sienori 
```javascript
  handleCopy = (copiedText) => {
    navigator.clipboard.writeText(copiedText);
    this.setState({ isCopied: true });
  };

```

**Comment by xeophyte** [comment]
> handleCopy = (copiedText) => {
    navigator.clipboard.writeText(copiedText);
    this.setState({ isCopied: true });
  };

What do I do with it? And where is this js file?

**Comment by sienori** [comment]
Thank you for your contribution!!
I merged your PR!
