### ISSUE TITLE
Feature request: add options to translate webpage in current tab, background new tab, or new window

### ISSUE THREAD

**Issue by d0mf1g** [sienori/simple-translate#74]
Currently using the translate web page feature opens the Google translate web page in a new foreground tab. It would be nice to also add other options in the settings page to "open in current tab," "open in new tab," "open in new tab and switch to the tab," and "open in new window."

**Comment by sienori** [comment]
Version 2.8.0 adds the option to open page translations in the current tab! 
![image](https://user-images.githubusercontent.com/29514424/187475648-d79c65bc-c5e1-44d6-8b60-700bb9f8536d.png)

**Comment by Alhadis** [comment]
@sienori This option only appears to exist in Chrome; Firefox has no such setting.

Translating an entire page should replace the current tab _by default_, because users aren't likely to refer back to the untranslated version, owing to the fact that they clear need translation to make sense of its contents.
